topics:
- name    : navigation
  topic   : nav_vel
  timeout : 0.5
  priority: 10
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 100
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 90
- name    : keyboard
  topic   : key_vel
  timeout : 0.5
  priority: 80
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255